spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/school_manage_system
        username: postgres
        password: 12345
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
application:
    security:
        admin:
            secret-key: "12345"
        jwt:
            secret-key: "wNNzWV9GkJQ6OJtWtAZ0umC032DqYYQ2mvBHl3mdjmYA9e8Scr/QWJqRCSvWK0vn"